// <auto-generated />
namespace CARMASTERY.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class general : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(general));
        
        string IMigrationMetadata.Id
        {
            get { return "202004241407315_general"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
